# Generated by Django 6.1.1 on 2026-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
