# Generated by Django 5.2.17 on 2026-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
