# Generated by Django 6.1.1 on 2026-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_idempotency_key_order_request_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PICKING', 'Picking'), ('SUBSTITUTION_REQUIRED', 'Substitution Required'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
    ]
